"""Add ai execution logs

Revision ID: af9a5ed80930
Revises: add_seq_id_columns
Create Date: 2026-01-16 14:59:57.172018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'af9a5ed80930'
down_revision: Union[str, None] = 'add_seq_id_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('step', sa.String(length=50), nullable=True),
    sa.Column('config_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('request_messages', sa.JSON(), nullable=True),
    sa.Column('response_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_execution_logs')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
